ingress-nginx:
  fullnameOverride: ingress-nginx
  controller:
    extraArgs:
      enable-ssl-passthrough: ''
    kind: DaemonSet
    watchIngressWithoutClass: true
    service:
      enabled: true
      externalTrafficPolicy: "Local"
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
    metrics:
      enabled: true
      serviceMonitor:
        enabled: false
