name: "Lint"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: .
          format: standard
          config_file: .yamllint.yml

  kubeval_manifests:
    name: "run kubeval on plain K8s manifests"
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: cedi-dev/gh-action-install-kubeval@main

      - name: Checkout
        uses: actions/checkout@v2

      - name: Manifests
        run: |
          for manifest in ./manifests/*/*.yaml
          do
            echo -n "$manifest"
            kubeval --ignore-missing-schemas --strict --schema-location https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/ $manifest
          done

  kubeval_charts:
    name: "run kubeval on charts"
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: cedi-dev/gh-action-install-kubeval@main

      - name: Checkout
        uses: actions/checkout@v2

      - name: Charts
        run: |
          for chart in ./charts/*/
          do
            echo "$chart"
              for app in $stage*/
              do
                  helm template $chart --values $chart/values.yaml | kubeval --ignore-missing-schemas --strict
              done
          done

  kubeval_kustomize:
    name: "run kubeval on Kustomize overlays"
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: cedi-dev/gh-action-install-kubeval@main

      - name: Checkout
        uses: actions/checkout@v2

      - name: Kustomize
        run: |
          for kust in ./kustomize/overlays/*/
          do
            echo "$kust"
            kustomize build --enable-alpha-plugins --enable-helm $kust | kubeval --ignore-missing-schemas --strict
          done
